config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :receipts

  resources :reports, :only => [:index, :show] do
    get 'monthly', :controller => "reports#show_monthly"
    get 'expense', :controller => "reports#show_expense"
  end

  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :receipt

  def amount
    price * quantity
  end
end

app/models/receipt.rb
class Receipt < ApplicationRecord
  has_many :items
  belongs_to :user
  accepts_nested_attributes_for :items, :reject_if => :all_blank, :allow_destroy => true

  def subtotal
    _subtotal = 0.0

    items.each do |item|
      _subtotal += item.amount
    end
  end

  def tax
    subtotal * (tax_rate / 100)
  end

  def total
    subtotal + tax
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :receipts
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
end

app/controllers/receipts_controller.rb
class ReceiptsController < ApplicationController
  def index
    @receipts = Receipt.where(:user_id => current_user.id).order(:purchase_date).reverse
  end

  def show
    @receipt = Receipt.find(params[:id])
  end

  def new
    @receipt = Receipt.new
  end

  def edit
    @receipt = Receipt.find(params[:id])
  end

  def create
    @receipt = Receipt.new(receipt_params)
    @receipt.user = current_user

    @receipt.purchase_date = receipt_params[:purchase_date].to_time
    @receipt.tax_rate = receipt_params[:tax_rate].to_f

    num = 0

    receipt_params[:items_attributes].map do |k, v|
      items = receipt_params[:items_attributes]
      item = items[k.to_s]
      @receipt.items[num].receipt = @receipt
      @receipt.items[num].price = item[:price].to_f
      @receipt.items[num].quantity = item[:quantity].to_i
      ++num
    end

    respond_to do |format|
      if @receipt.save
        format.html { redirect_to(@receipt, :notice => 'Receipt was successfully created.') }
      else
        flash[:notice] = @receipt.errors.full_messages
        format.html { render :action => 'new' }
      end
    end
  end

  def update
    @receipt = Receipt.find(params[:id])
    @receipt.user = current_user

    respond_to do |format|
      if @receipt.update_attributes(receipt_params)
        format.html { redirect_to(@receipt, :notice => 'Receipt was successfully updated.') }
      else
        format.html { render :action => 'new' }
      end
    end
  end

  def destroy
    @receipt = Receipt.find(params[:id])
    @receipt.destroy

    respond_to do |format|
      format.html { redirect_to(receipts_url) }
    end
  end

  def receipt_params
    params.require(:receipt).permit(
      :display_name, :purchase_date, :tax_rate, :payment_type, :user_id,
      items_attributes: [:id, :category, :quantity, :description, :price, :_destroy]
    )
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def index

  end

  def show
    @receipts = Receipt.find(params[:id])
  end

  def show_monthly
  end

  def show_expense
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/receipt_helper.rb
module ReceiptHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Receipt</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>



  <body>

  <nav class="navbar navbar-toggleable-md navbar-light bg-purple">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="#">Receipts</a>

    <div class="collapse navbar-collapse justify-content-between" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'Receipts', receipts_url, :class => "nav-link" %>
          </li>
        <% end %>
      </ul>
      <ul class="navbar-nav">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'Settings',  edit_user_registration_url, :class => "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign Out',  destroy_user_session_url, :class => "nav-link", :method => :delete %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Sign In',  new_user_session_url, :class => "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Register',  new_user_registration_url, :class => "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>
    <% if flash[:notice] != nil %>
    <p class="notice alert alert-success" role="alert"><%= flash[:notice] %></p>
    <% end %>
    <% if flash[:alert] != nil %>
    <p class="alert alert-danger"><%= flash[:alert] %></p>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/receipt/new.html.erb
<%= form_for :receipt do |f| %>
  <div class="form-group">
    <%= f.label(:receipt, :display_name) %>
    <%= f.text_field :display_name %>
  </div>

  <button type="submit" class="btn btn-primary">Submit</button>
  <%= f.submit %>
<% end %>

app/views/receipts/_form.html.erb
<%= form_for @receipt do |f| %>
  <div class="form-group">
    <%= f.label :display_name, 'Title' %>
    <%= f.text_field :display_name, :class => 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :purchase_date, 'Date' %>
    <%= f.text_field :purchase_date, 'data-provide': 'datepicker', :class => 'form-control' %>
  </div>

  <div class="form-group items">
    <div class="row">
      <div class="col-sm-2">
        Qty.
      </div>
      <div class="col-sm-6">
        Description
      </div>
      <div class="col-sm-2">
        Price
      </div>
      <div class="col-sm-2">
      </div>
    </div>

    <%= f.simple_fields_for :items do |item| %>
      <%= render 'item_fields', :f => item %>
    <% end %>

    <div>
      <%= link_to_add_association '+', f, :items, :class => 'btn btn-secondary float-right' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :tax_rate, 'Tax Rate (%)' %>
    <%= f.text_field :tax_rate, :class => 'form-control' %>
  </div>


    <div class="form-group">
      <%= f.label :payment_type, 'Payment Type' %>
      <%= f.select :payment_type, options_for_select([["Cash", 0], ["Debit Card", 1], ["Credit Card", 2]]), {}, { :class => 'form-control' } %>
    </div>

  <%= f.submit 'Submit', :class => 'btn btn-primary' %>
<% end %>

app/views/receipts/_item.html.erb
<div class="row">
  <div class="col-sm-2">
    <%= item.quantity %>
  </div>
  <div class="col-sm-6">
    <%= item.description %>
  </div>
  <div class="col-sm-2">
    <%= number_to_currency(item.price) %>
  </div>
  <div class="col-sm-2">
    <%= number_to_currency(item.amount) %>
  </div>
</div>

app/views/receipts/_item_fields.html.erb
<div class="row">
  <div class="col-sm-2">
    <%= f.text_field :quantity, :class => 'form-control' %>
  </div>
  <div class="col-sm-6">
    <%= f.text_field :description, :class => 'form-control' %>
  </div>
  <div class="col-sm-2">
    <%= f.text_field :price, :class => 'form-control' %>
  </div>
  <div class="col-sm-2">
  </div>
</div>

app/views/receipts/edit.html.erb
<div class="row justify-content-center">
  <div class="col-sm-6">
    <h2>Edit Receipt</h2>
    <%= render 'form' %>
  </div>
</div>

app/views/receipts/index.html.erb
<div class="row justify-content-center">
  <div class="col-sm-6">
    <h2>
      Receipts for <%= current_user.email %>
    </h2>

    <div class="row">
      <% @receipts.each do |receipt| %>
        <div class="col-sm-6">
          <%= link_to receipt.display_name, receipt_url(receipt) %>
        </div>
        <div class="col-sm-3">
          <%= receipt.purchase_date.strftime('%m/%d/%Y') %>
        </div>
        <div class="col-sm-3">
          <%= link_to 'Edit', edit_receipt_url(receipt) %>
          <%= link_to 'Delete', receipt_url(receipt), :method => 'delete', data: {confirm: "Are you sure you want to delete the receipt?"} %>
        </div>
      <% end %>
    </div>

    <div class="row" style="padding-top:20px">
      <%= link_to 'New Receipt', new_receipt_url, :class => 'btn btn-primary' %>
    </div>
  </div>
</div>

app/views/receipts/new.html.erb
<div class="row justify-content-center">
  <div class="col-sm-6">
    <h2>New Receipt</h2>
    <%= render 'form' %>
  </div>
</div>

app/views/receipts/show.html.erb
<div class="row justify-content-center">
  <div class="col-sm-6">
    <h2>
      <%= @receipt.display_name %> - <%= @receipt.purchase_date.strftime('%m/%d/%Y') %>
    </h2>

    <div class="row">
      <div class="col-sm-2">
        Qty.
      </div>
      <div class="col-sm-6">
        Description
      </div>
      <div class="col-sm-2">
        Price
      </div>
      <div class="col-sm-2">
        Amount
      </div>
    </div>

    <%= render partial: 'item', collection: @receipt.items %>

    <hr />

    <div class="row">
      <div class="col-sm-8"> </div>
      <div class="col-sm-2">
        Subtotal
      </div>
      <div class="col-sm-2">
        <%= number_to_currency(@receipt.items.sum(&:amount)) %>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-8"> </div>
      <div class="col-sm-2">
        Tax (<%= number_to_percentage(@receipt.tax_rate, :strip_insignificant_zeros => true) %>)
      </div>
      <div class="col-sm-2">
        <%= number_to_currency(@receipt.items.sum(&:amount) * @receipt.tax_rate / 100) %>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-8"> </div>
      <div class="col-sm-2">
        Total
      </div>
      <div class="col-sm-2">
        <%= number_to_currency(@receipt.items.sum(&:amount) + @receipt.items.sum(&:amount) * @receipt.tax_rate / 100) %>
      </div>
    </div>
  </div>
</div>